spring:
  cloud:
    config:
      enabled: false
server:
  port: 8080
management:
  endpoint:
    refresh:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: refresh,health,info
logging:
  level:
    org.springframework.boot.actuate: debug

my:
  custom:
    property: "Initial Value"