spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    show-sql: true
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: admin
#    properties:
#      hibernate:
#        format_sql: true
logging:
  level:
    org:
      hibernate: WARN
server:
  error:
    include-stacktrace: ON_PARAM # show or not error stacktrace in response