spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

    show-sql: true
  #    show-sql: true # show sql request in console
#    properties:
#      hibernate:
#        format_sql: true
logging:
  level:
    org:
#      springframework:
#        web: DEBUG
      hibernate: DEBUG
server:
  error:
    include-stacktrace: ON_PARAM # show or not error stacktrace in response