spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: admin
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org:
      hibernate: WARN
server:
  error:
    include-stacktrace: ON_PARAM # show or not error stacktrace in response
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui
token:
  signing:
    key: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
